version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: install deps for wkhtmltopdf
          command: sudo apt-get update && sudo apt-get install -y libjpeg8-dev libxrender1 libfontconfig1
      - run:
          name: DB Setup
          command: bundle exec rake db:schema:load
      - run:
          name: Tests
          command: bundle exec rake test
